function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('charger', '2018 Dodge Charger Police')
    AddTextEntry('crownvic', '2011 Crown Victoria Police')
    AddTextEntry('tahoe', '2020 Chevy Tahoe Police')
    AddTextEntry('durango', '2019 Dodge Durango Police')
    AddTextEntry('f250', '2016 Ford F250 Police')
    AddTextEntry('taurus', '2016 Ford Taurus Police')
    AddTextEntry('2015polstang', '2015 Ford Mustang Police')
    AddTextEntry('hillboaty', 'Police Boat')
end)
