function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('AUDI_01', 'AUDI_1')
    AddTextEntry('AUDI_02', 'AUDI_2')
    AddTextEntry('AUDI_03', 'AUDI_3')
    AddTextEntry('AUDI_04', 'AUDI_4')
    AddTextEntry('AUDI_06', 'AUDI_6')
    AddTextEntry('AUDI_07', 'AUDI_7')
    AddTextEntry('AUDI_09', 'AUDI_9')
    AddTextEntry('AUDI_10', 'AUDI_10')
    AddTextEntry('AUDI_11', 'AUDI_11')
    AddTextEntry('AUDI_12', 'AUDI_12')
    AddTextEntry('AUDI_13', 'AUDI_13')
    AddTextEntry('AUDI_14', 'AUDI_14')
    AddTextEntry('AUDI_15', 'AUDI_15')
    AddTextEntry('AUDI_16', 'AUDI_16')
    AddTextEntry('AUDI_17', 'AUDI_17')
    AddTextEntry('AUDI_18', 'AUDI_18')
    AddTextEntry('AUDI_19', 'AUDI_19')
    AddTextEntry('AUDI_20', 'AUDI_20')
    AddTextEntry('AUDI_21', 'AUDI_21')
    AddTextEntry('AUDI_22', 'AUDI_22')
    AddTextEntry('AUDI_24', 'AUDI_24')
    AddTextEntry('99VIP_RIM01', 'Viper Wheel')
    AddTextEntry('GENERALLEE_01', 'General Lee Wheel')
    AddTextEntry('M19_RIM_1', 'M19 Wheel 1')
    AddTextEntry('M19_RIM_2', 'M19 Wheel 2')
    AddTextEntry('M19_RIM_3', 'M19 Wheel 3')
    AddTextEntry('M19_RIM_4', 'M19 Wheel 4')
    AddTextEntry('M19_RIM_5', 'M19 Wheel 5')
    AddTextEntry('M19_RIM_6', 'M19 Wheel 6')
    AddTextEntry('M19_RIM_7', 'M19 Wheel 7')
    AddTextEntry('en01', 'JDM Wheel 1')
    AddTextEntry('mgp', 'JDM Wheel 2')
    AddTextEntry('re30', 'JDM Wheel 3')
    AddTextEntry('agt1', 'JDM Wheel 4')
    AddTextEntry('agt2', 'JDM Wheel 5')
    AddTextEntry('cr01', 'JDM Wheel 6')
    AddTextEntry('rpf1', 'JDM Wheel 7')
    AddTextEntry('rp03', 'JDM Wheel 8')
    AddTextEntry('te37', 'JDM Wheel 9')
    AddTextEntry('te37v', 'JDM Wheel 10')
    AddTextEntry('sa60', 'JDM Wheel 11')
    AddTextEntry('bt3', 'JDM Wheel 12')
    AddTextEntry('rg2', 'JDM Wheel 13')
    AddTextEntry('p45r', 'JDM Wheel 14')
    AddTextEntry('mf10', 'JDM Wheel 15')
    AddTextEntry('sw388', 'JDM Wheel 16')
    AddTextEntry('5gn', 'JDM Wheel 17')
    AddTextEntry('57c6', 'JDM Wheel 18')
    AddTextEntry('rs050rr', 'JDM Wheel 19')
    AddTextEntry('ms1', 'JDM Wheel 20')
    AddTextEntry('wrs', 'JDM Wheel 21')
    AddTextEntry('ms01', 'JDM Wheel 22')
    AddTextEntry('ce28', 'JDM Wheel 23')
    AddTextEntry('e40', 'JDM Wheel 24')
    AddTextEntry('ml1', 'JDM Wheel 25')
    AddTextEntry('mk2r', 'JDM Wheel 26')
    AddTextEntry('blm', 'JDM Wheel 27')
    AddTextEntry('lg4', 'JDM Wheel 28')
    AddTextEntry('lg1', 'JDM Wheel 29')
    AddTextEntry('gtc', 'JDM Wheel 30')
    AddTextEntry('dh', 'JDM Wheel 31')
    AddTextEntry('jps', 'JDM Wheel 32')
    AddTextEntry('svk', 'JDM Wheel 33')
    AddTextEntry('sv', 'JDM Wheel 34')
    AddTextEntry('037', 'JDM Wheel 35')
    AddTextEntry('rnr', 'JDM Wheel 36')
    AddTextEntry('vskf', 'JDM Wheel 37')
    AddTextEntry('vsxx', 'JDM Wheel 38')
    AddTextEntry('cst', 'JDM Wheel 39')
    AddTextEntry('fe', 'JDM Wheel 40')
    AddTextEntry('sfm', 'JDM Wheel 41')
    AddTextEntry('sfm2', 'JDM Wheel 42')
    AddTextEntry('sss', 'JDM Wheel 43')
    AddTextEntry('sps3', 'JDM Wheel 44')
    AddTextEntry('eav', 'JDM Wheel 45')
    AddTextEntry('bp1', 'JDM Wheel 46')
    AddTextEntry('ete', 'JDM Wheel 47')
    AddTextEntry('tsl', 'JDM Wheel 48')
    AddTextEntry('mle', 'JDM Wheel 49')
    AddTextEntry('ozr', 'JDM Wheel 50')
    AddTextEntry('we1', 'JDM Wheel 51')
    AddTextEntry('dyc', 'JDM Wheel 52')
    AddTextEntry('fm1', 'JDM Wheel 53')
    AddTextEntry('SUBNLTZ', 'Subnltz')
    AddTextEntry('SUBNHD', 'Subnhd')
    AddTextEntry('DAYTONS1', 'Daytons 1')
    AddTextEntry('DAYTONS2', 'Daytons 2')
    AddTextEntry('DAYTONS3', 'Daytons 3')
    AddTextEntry('DAYTONS4', 'Daytons 4')
    AddTextEntry('DAYTONS5', 'Daytons 5')
    AddTextEntry('DAYTONS6', 'Daytons 6')
    AddTextEntry('DAYTONS7', 'Daytons 7')
    AddTextEntry('DAYTONS8', 'Daytons 8')
    AddTextEntry('DAYTONS9', 'Daytons 9')
    AddTextEntry('DAYTONS10', 'Daytons 10')
    AddTextEntry('DAYTONS11', 'Daytons 11')
    AddTextEntry('DAYTONS12', 'Daytons 12')
    AddTextEntry('DAYTONS13', 'Daytons 13')
    AddTextEntry('DAYTONS14', 'Daytons 14')
    AddTextEntry('DAYTONS15', 'Daytons 15')
    AddTextEntry('DAYTONS16', 'Daytons 16')
    AddTextEntry('DAYTONS17', 'Daytons 17')
    AddTextEntry('DAYTONS18', 'Daytons 18')
    AddTextEntry('DAYTONS19', 'Daytons 19')
    AddTextEntry('DAYTONS20', 'Daytons 20')
    AddTextEntry('DAYTONS21', 'Daytons 21')
    AddTextEntry('DAYTONS22', 'Daytons 22')
    AddTextEntry('DAYTONS23', 'Daytons 23')
    AddTextEntry('DAYTONS24', 'Daytons 24')
    AddTextEntry('DAYTONS25', 'Daytons 25')
    AddTextEntry('DAYTONS26', 'Daytons 26')
    AddTextEntry('DAYTONS27', 'Daytons 27')
    AddTextEntry('DAYTONS28', 'Daytons 28')
    AddTextEntry('DAYTONS29', 'Daytons 29')
    AddTextEntry('DAYTONS30', 'Daytons 30')
    AddTextEntry('DAYTONS31', 'Daytons 31')
    AddTextEntry('DAYTONS32', 'Daytons 32')
    AddTextEntry('DAYTONS33', 'Daytons 33')
    AddTextEntry('DAYTONS34', 'Daytons 34')
    AddTextEntry('DAYTONS35', 'Daytons 35')
    AddTextEntry('DAYTONS36', 'Daytons 36')
    AddTextEntry('VOSSEN VPS305 Matte', 'VOSSEN VPS305 Matte')
    AddTextEntry('VOSSEN VFS2', 'VOSSEN VFS2')
    AddTextEntry('VOSSEN VFS2 Camber', 'VOSSEN VFS2 Camber')
    AddTextEntry('Glossy M Sport', 'Glossy M Sport')
    AddTextEntry('Enkei RS05RR', 'Enkei RS05RR')
    AddTextEntry('Enkei RS05RR Camber', 'Enkei RS05RR Camber')
    AddTextEntry('Z4_sport_1', 'BMW Z4 Sport')

    
end)