function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('BRIMSVO_01', 'Brimsvo Wheel 1')
    AddTextEntry('BRIMSVO_02', 'Brimsvo Wheel 2')
    AddTextEntry('BRIMSVO_03', 'Brimsvo Wheel 3')
    AddTextEntry('BRIMSVO_04', 'Brimsvo Wheel 4')
    AddTextEntry('BRIMSVO_05', 'Brimsvo Wheel 5')
    AddTextEntry('BRIMSVO_06', 'Brimsvo Wheel 6')
    AddTextEntry('BRIMSVO_07', 'Brimsvo Wheel 7')
    AddTextEntry('BRIMSVO_08', 'Brimsvo Wheel 8')
    AddTextEntry('BRIMSVO_09', 'Brimsvo Wheel 9')
    AddTextEntry('BRIMSVO_10', 'Brimsvo Wheel 10')
    AddTextEntry('BRIMSVO_11', 'Brimsvo Wheel 11')
    AddTextEntry('BRIMSVO_12', 'Brimsvo Wheel 12')
    AddTextEntry('BRIMSVO_13', 'Brimsvo Wheel 13')
    AddTextEntry('BRIMSVO_14', 'Brimsvo Wheel 14')
    AddTextEntry('BRIMSVO_15', 'Brimsvo Wheel 15')
    AddTextEntry('BRIMSVO_16', 'Brimsvo Wheel 16')
    AddTextEntry('BRIMSVO_17', 'Brimsvo Wheel 17')
    AddTextEntry('BRIMSVO_18', 'Brimsvo Wheel 18')
    AddTextEntry('BRIMSVO_19', 'Brimsvo Wheel 19')
    AddTextEntry('BRIMSVO_20', 'Brimsvo Wheel 20')
    AddTextEntry('BRIMSVO_21', 'Brimsvo Wheel 21')
    AddTextEntry('AUDI_1', 'AUDI_1')
    AddTextEntry('AUDI_2', 'AUDI_2')
    AddTextEntry('AUDI_2', 'AUDI_3')
    AddTextEntry('AUDI_4', 'AUDI_4')
    AddTextEntry('AUDI_5', 'AUDI_5')
    AddTextEntry('AUDI_6', 'AUDI_6')
    AddTextEntry('AUDI_7', 'AUDI_7')
    AddTextEntry('AUDI_8', 'AUDI_8')
    AddTextEntry('AUDI_9', 'AUDI_9')
    AddTextEntry('AUDI_10', 'AUDI_10')
    AddTextEntry('AUDI_11', 'AUDI_11')
    AddTextEntry('AUDI_12', 'AUDI_12')
    AddTextEntry('AUDI_13', 'AUDI_13')
    AddTextEntry('AUDI_14', 'AUDI_14')
    AddTextEntry('AUDI_15', 'AUDI_15')
    AddTextEntry('AUDI_16', 'AUDI_16')
    AddTextEntry('AUDI_17', 'AUDI_17')
    AddTextEntry('AUDI_18', 'AUDI_18')
    AddTextEntry('AUDI_19', 'AUDI_19')
    AddTextEntry('AUDI_20', 'AUDI_20')
    AddTextEntry('AUDI_21', 'AUDI_21')
    AddTextEntry('AUDI_22', 'AUDI_22')
    AddTextEntry('AUDI_24', 'AUDI_24')
    
end)