var ROOT_ADDRESS = 'http://pw_phone';

var entityMap = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
    '`': '&#x60;',
    '=': '&#x3D;'
};

var Apps = [
    {
        name: 'Contacts',
        container: 'contacts',
        icon: '<i class="fas fa-address-book"></i>',
        color: '#006064',
        unread: 0,
        enabled: true,
        installable: false,
        uninstallable: false,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: false,
        description: "This application stores and manages your contacts to be able to call and text."
    },
    {
        name: 'Phone',
        container: 'phone',
        icon: '<i class="fas fa-phone"></i>',
        color: '#01579b',
        unread: 0,
        enabled: true,
        installable: false,
        uninstallable: false,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: false,
        description: "This application enables your phone to make and receive telephone calls."
    },
    {
        name: 'Messages',
        container: 'message',
        icon: '<i class="fas fa-comment-alt"></i>',
        color: '#311b92',
        unread: 0,
        enabled: true,
        installable: false,
        uninstallable: false,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: false,
        description: "This application enables your phone to send and receive text (SMS) messages."
    },
    {
        name: 'Bank',
        container: 'bank',
        icon: '<i class="fas fa-university"></i>',
        color: '#d7252a',
        unread: 0,
        enabled: true,
        installable: true,
        uninstallable: true,
        customExit: true,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: true,
        description: "This application is provided by SynCity Banking, to enable transactions performed on your phone."
    },
    {
        name: 'Twitter',
        container: 'twitter',
        icon: '<i class="fab fa-twitter"></i>',
        color: '#039be5',
        unread: 1,
        enabled: true,
        installable: true,
        uninstallable: true,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: false,
        description: "Twitter is one of the top Social Media Networking websites avaliable in our city."
    },
    {
        name: 'Yellow Pages',
        container: 'yp',
        icon: '<i class="fas fa-ad"></i>',
        color: '#f9a825',
        unread: 0,
        enabled: true,
        installable: true,
        uninstallable: true,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: false,
        description: "Looking for advertisements? Sales? Services? the Yellow Pages is for you."
    },
    {
        name: 'Settings',
        container: 'settings',
        icon: '<i class="fas fa-cogs"></i>',
        color: '#404040',
        unread: 0,
        enabled: true,
        installable: false,
        uninstallable: false,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: false,
        description: "This application enables you to edit and update settings regarding your phone."
    },
    {
        name: 'App Store',
        container: 'store',
        icon: '<i class="fas fa-cogs"></i>',
        color: '#404040',
        unread: 0,
        enabled: true,
        installable: false,
        uninstallable: false,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: false,
        description: "This application enables you to install and uninstall applications from the Application Store."
    },
    {
        name: 'Fake Chrome',
        container: 'chrome',
        icon: '<i class="fas fa-cogs"></i>',
        color: '#404040', 
        unread: 0,
        enabled: true,
        installable: true,
        uninstallable: true,
        dumpable: 0,
        public: true,
        jobRequired: Array(),
        customExit: true,
        description: ""
    },
    {
        name: 'MDT',
        container: 'mdt',
        icon: '<i class="fas fa-cogs"></i>',
        color: '#404040', 
        unread: 0,
        enabled: true,
        installable: true,
        uninstallable: true,
        dumpable: 0,
        public: true,
        jobRequired: [4],
        customExit: true,
        description: "",
    },
];


export default { ROOT_ADDRESS, entityMap, Apps };